name: Terraform EKS Setup

on:
  push:
    branches:
    - master

jobs:
  setup-eks-and-addons:
    name: Setup EKS Cluster and Install Addons
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-west-2

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      if: github.event_name == 'push'
      run: terraform plan -no-color
      continue-on-error: true

    - name: Terraform Apply
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: terraform apply -auto-approve

    - name: Configure kubectl
      run: aws eks --region us-west-2 update-kubeconfig --name okpataku-c

  run-scripts:
    name: Run Scripts
    runs-on: ubuntu-latest
    needs: setup-eks-and-addons

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run Kyverno Script
      run: |
        # Replace with your script execution command
        sh scripts/kyverno.sh
